market_research:
  description: >
    调查微博上与该微博账户所属行业相关的最新趋势、标签和竞争对手活动。重点收集能揭示哪些内容在本年度表现良好的数据，确定模式、偏好和新兴趋势。 

    当前时间: {current_date}

    您正在进行研究的微博帐户的描述：  
    <WEIBO_ACCOUNT_DESCRIPTION>{weibo_description}</WEIBO_ACCOUNT_DESCRIPTION>

    找到最相关的话题、标签和趋势，用于下周的文章。下周的重点如下： 
    <NEXT_WEEK_CONTENT>{topic_of_the_week}</NEXT_WEEK_CONTENT>

  expected_output: >
    一份报告，其中包含您发现的最相关信息，包括与本周内容相关的标签，以及对内容创作团队有用的所有其他信息。

content_strategy:
  description: >
    根据市场调研结果，制定一周的综合内容日程表。日程表应明确一周（从周一到周日）每天的主题，在这一天应发布一些内容，并提出发布内容的初步想法。目前，应将重点放在为期三天的内容日程表上，包括在每个帖子中使用的最相关的关键词和标签。
  expected_output: >
    详细的一周内容日程，格式为 markdown ,其中包括一周中的哪几天（从周一到周五）、内容创意概述以及每篇文章中要使用的最相关的关键词和标签。确保日程符合已确定的趋势和受众偏好。

visual_content_creation:
  description: >
    根据每篇微博帖子的内容策略，创建一周中每天将在微博上发布的视觉艺术。为此，你需要为每天要使用的图片创建详细的描述。
    你要使用的描述既要详细，又要简洁，还应包括图片中应出现的主要元素。描述颜色、物体、情绪以及任何其他你认为对创建图像很重要的相关信息。

    以下是一些您可以使用的描述示例：
    - 一个具有现代设计风格的客厅的真实图像。房间应该有一扇大窗户，可以看到城市风景。色调应该是中性的，并以红色沙发作为点缀。房间应光线充足，氛围舒适宜人。
    - 一张简约的办公桌，上面摆放着一台笔记本电脑、一本笔记本和一杯咖啡。书桌应为浅色木质，背景应为纯白色墙壁。图片应传达出一种专注和高效的感觉。
    - 日落时分的热带海滩，充满活力。海滩应该是荒凉的，棕榈树在风中摇曳。天空应是暖色调的混合，太阳落在地平线上。画面应唤起一种放松和宁静的感觉。

  expected_output: >
    一份 Markdown 文件，详细描述本周微博发布的每篇文章将使用的图片。每张图片的描述都应简明扼要，包括主要元素、颜色、基调和任何其他相关信息，以指导图片的创作。描述应与内容日程和确定的趋势保持一致。

copywriting:
  description: >
    根据内容日历的战略主题，为每周的微博帖子撰写引人入胜的相关文案。文案应吸引受众，体现品牌声音，鼓励互动。文案还应有利于搜索引擎优化，并包含内容日程表中的相关关键词和标签。

    在撰写文案时，请考虑以下指导原则：
    - 文案应简洁明了、引人入胜。
    - 在适当的地方加入行动号召。
    - 使用相关关键词和标签。
    - 确保文案符合品牌的声音和语气。

    以下是您可以使用的一些文案示例：
    - 大家好！我们很高兴与您分享我们的最新系列。查看我们的网站，了解更多详情。#新系列#时尚#风格"
    - 周一快乐 :sunflower: 用我们美味的冰沙开始您一周的美好时光。今天就访问我们的商店！#moothies #healthyliving #mondaymotivation" 
    - 感觉压力很大？来享受一天放松的水疗吧。现在预订，尽享奢华。#spaday #relaxation #selfcare" 
  expected_output: >
    一份格式为 markdown 的文档，包含多个部分。每个部分都应包含一篇微博帖子的文案，以及相关的标签和行动号召。文案应引人入胜、符合品牌形象，并与内容日程保持一致。

report_final_content_strategy:
  description: >
    编写一份综合报告，概述本周的最终内容策略。报告应包括市场调研结果、内容日程表、每篇文章的文案以及人工智能生成的图片。简要说明策略的基本原理，解释该策略如何与已确定的趋势和受众偏好保持一致。

  expected_output: >
    一份详细的报告，包括市场调研结果、内容日程表、每篇文章的文案以及人工智能生成的图片。报告应采用 markdown 格式，并简要说明策略的基本原理，解释如何与已确定的趋势和受众偏好保持一致。
