market_research:
  description: >
    调查微博上与该微博账户所属行业相关的最新趋势、标签和竞争对手活动。重点收集能揭示哪些内容在本年度表现良好的数据，确定模式、偏好和新兴趋势。

    当前日期: {current_date}

    您正在进行研究的微博帐户的描述：  
    <WEIBO_ACCOUNT_DESCRIPTION>{weibo_description}</WEIBO_ACCOUNT_DESCRIPTION>

    寻找下周帖子中使用的最相关的话题、标签和趋势。下周的重点内容如下：
    <NEXT_WEEK_CONTENT>{topic_of_the_week}</NEXT_WEEK_CONTENT>

  expected_output: >
    一份包含您发现的最相关信息的报告，包括本周内容的相关标签和所有其他对内容创作团队有用的信息。

content_strategy:
  description: >
    根据市场研究结果，为一周内每天（从周一到周日）发帖制定全面的内容日历。现在，重点是为三天的内容日历制定初步的帖子内容想法，包括每篇帖子中使用的最相关的关键词和标签。
  expected_output: >
    一份详细的为期一周的内容日历，格式为markdown，包括一周中的每天（从周一到周五），内容想法的简要概述，以及每篇帖子中使用的最相关的关键词和标签。确保日历与识别的趋势和受众偏好保持一致。

visual_content_creation:
  description: >
    根据每篇微博帖子的内容策略，创建将在一周中每天发布在微博上的视觉艺术作品。为此，您需要为每天使用的图像创建详细的描述。
    您将使用的描述应详细而简洁，并应包括图像中应呈现的主要元素。描述颜色、物体、氛围和您认为对创建图像重要的任何其他相关信息。

    这里有一些您可以使用的描述示例：
    - 一个现代设计的客厅的逼真图像。房间应有一个大窗户，可以看到城市景观。色彩方案应为中性，以红色沙发的形式增添一抹色彩。房间应该光线充足，氛围温馨而邀请。
    - 一个简约的带有笔记本电脑、笔记本和一杯咖啡的桌子的图像。桌子应该是浅色木头制成的，背景应该是一面简单的白墙。图像应传达专注和生产力的感觉。
    - 日落时分的热带海滩的生动图像。海滩应该是空无一人的，有风中摇曳的棕榈树。天空应该是温暖色彩的混合，太阳正沉落在地平线上。图像应该唤起放松和宁静的感觉。

  expected_output: >
    一份markdown格式的文档，包含一周内每篇微博帖子将使用的图像的详细描述。每个描述应简洁并包括主要元素、颜色、氛围和任何其他相关信息，这些信息将指导图像的创建。描述应与内容日历和识别的趋势保持一致。

copywriting:
  description: >
    为一周内每篇微博帖子撰写引人入胜且相关的文案，与内容日历的战略主题保持一致。文案应吸引受众，体现品牌声音，并鼓励互动。文案还应具有SEO友好性，并融入内容日程中包含的相关关键词和标签。

    撰写文案时请考虑以下指南：
    - 保持文案简洁且引人入胜。
    - 在适当的地方包括行动号召。
    - 使用相关的关键词和标签。
    - 确保文案与品牌的声音和调性保持一致。

    这里有一些您可以使用的文案示例：
    - “大家好！:heart: 我们很高兴与您分享我们的最新系列。更多详情请访问我们的网站。#新系列 #时尚 #风格”
    - “快乐的周一！:sunflower: 用我们的美味果昔正确开始您的一周。今天就来我们的店吧！#果昔 #健康生活 #周一动力”
    - “感觉压力很大？:massage: 来享受一天放松的水疗吧。现在预订，尽享奢华。#水疗日 #放松 #自我关怀”
  expected_output: >
    一份格式为markdown的文档，包含几个部分。每个部分都应包含一篇微博帖子的文案，以及相关的标签和行动号召。文案应引人入胜、符合品牌形象，并与内容日程保持一致。

report_final_content_strategy:
  description: >
    编写一份综合报告，概述本周的最终内容策略。报告应包括市场调研结果、内容日程表、每篇文章的文案以及人工智能生成的图片。简要说明策略的基本原理，解释该策略如何与已确定的趋势和受众偏好保持一致。

  expected_output: >
    一份详细的报告，包括市场调研结果、内容日程表、每篇文章的文案以及人工智能生成的图片。报告应采用markdown格式，并简要说明策略的基本原理，解释如何与已确定的趋势和受众偏好保持一致。